version: "3.3"
services:
  timeflow:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    environment:
      - NEXT_PUBLIC_API_PREFIX=http://94.12.185.96:3001/api/
      - NEXT_PUBLIC_GITHUB_CLIENT_ID=7125ed4d07c9867c0c74
      - ENSEMBLE_ROOT=/tmp/ensemble_root
      - TIMEFLOW_CI_SERVER=http://${SERVER_IP_ADDRESS}:3002
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    volumes:
      - /tmp/ensemble_root:/tmp/ensemble_root

