# fly.toml file generated for timeflow on 2023-03-25T14:12:58Z

app = "timeflow"
kill_timeout = 0
primary_region = "lhr"

[env]
  ENSEMBLE_ROOT = "/tmp/ensemble_root"
  GITHUB_CLIENT_ID = "7125ed4d07c9867c0c74"
  GITHUB_CLIENT_SECRET = "c367e32cbd12bb42e4af415ef2bafd098a2d45e6"
  NEXT_PUBLIC_API_PREFIX = "http://localhost:3001/api/"
  NEXT_PUBLIC_GITHUB_CLIENT_ID = "7125ed4d07c9867c0c74"
  TIMEFLOW_CI_SERVER = "https://timeflow.fly.dev:3002"

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 3000
    handlers = ["tls", "http"]

[[services]]
  protocol = "tcp"
  internal_port = 3001

  [[services.ports]]
    port = 3001
    handlers = ["tls", "http"]

[[services]]
  protocol = "tcp"
  internal_port = 3002

  [[services.ports]]
    port = 3002
    handlers = ["tls", "http"]
